add: onClick
bclabs-org/meut-ui-react pull request #35
Opened 2022-12-22 06:35 UTC by bclabs-kate

# Issue
link url https://bclabs.atlassian.net/browse/PLAYV-1021

# What fix
- onClick 추가

2022-12-22 07:18 UTC, bclabs-theo requested changes

2022-12-22 07:18 UTC, bclabs-theo commented on src/components/Button/Button.tsx
> +  return <button {...rest} disabled={disabled} onClick={onClick} className={`${styleClass} rounded-100 text-white font-bold flex justify-center items-center disabled:opacity-40`}>
컨벤션이 handleClick이지 않아요~?

2022-12-22 07:20 UTC, bclabs-theo commented on src/components/Button/Button.tsx
> +  return <button {...rest} disabled={disabled} onClick={onClick} className={`${styleClass} rounded-100 text-white font-bold flex justify-center items-center disabled:opacity-40`}>
컨벤션이 handleClick이지 않아요~?

2022-12-22 07:36 UTC, bclabs-theo approved these changes
👍👍👍👍👍

2022-12-22 07:52 UTC, bclabs-paul submitted a review, later dismissed
✨✨✨✨✨

2022-12-23 01:02 UTC, bclabs-theo submitted a review, later dismissed
고생했어요!

2022-12-23 01:21 UTC, bclabs-ted submitted a review, later dismissed

2022-12-23 01:27 UTC, bclabs-theo approved these changes

2022-12-23 01:34 UTC, bclabs-paul approved these changes
⭐️⭐️⭐️⭐️⭐️

2022-12-23 01:40 UTC, bclabs-ted approved these changes

2022-12-23 01:52 UTC, merged